In [4]:
from pyspark.sql import SparkSession
import pyspark.sql.functions as F
spark = SparkSession.builder.appName("Read Parquet").getOrCreate()
# read in all the data across the times
year_2026_01 = spark.read.parquet("data/year-2026/yellow_tripdata_2026-01.parquet")
year_2026_02 = spark.read.parquet("data/year-2026/yellow_tripdata_2026-02.parquet")
year_2026_03 = spark.read.parquet("data/year-2026/yellow_tripdata_2026-03.parquet")
year_2026_04 = spark.read.parquet("data/year-2026/yellow_tripdata_2026-04.parquet")
year_2026_05 = spark.read.parquet("data/year-2026/yellow_tripdata_2026-05.parquet")
data = year_2026_01.union(year_2026_02).union(year_2026_03).union(year_2026_04).union(year_2026_05)
data.printSchema()

root
 |-- VendorID: integer (nullable = true)
 |-- tpep_pickup_datetime: timestamp_ntz (nullable = true)
 |-- tpep_dropoff_datetime: timestamp_ntz (nullable = true)
 |-- passenger_count: long (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- RatecodeID: long (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- PULocationID: integer (nullable = true)
 |-- DOLocationID: integer (nullable = true)
 |-- payment_type: long (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- Airport_fee: double (nullable = true)
 |-- cbd_congestion_fee: double (nullable = true)

In [5]:
print(data.count())
data.select('tpep_pickup_datetime').distinct().count()

18999282

8781561

# Calculating trip duration and revenue per minute

In [ ]:
data1 = data
data1 = data1.withColumn('duration_minute', F.timestamp_diff('MINUTE', 'tpep_pickup_datetime', 'tpep_dropoff_datetime'))
zone_stats = data1.groupby('PULocationID').agg({'total_amount': 'sum', 'duration_minute': 'sum'}).withColumnsRenamed({'sum(duration_minute)': 'total_min', 'sum(total_amount)': 'total_revenue'}) 
zone_stats = zone_stats.withColumn('revenue_per_min', F.col('total_revenue')/F.col('total_min'))
zone_stats.show()

+------------+------------------+---------+------------------+------------------+
|PULocationID|     total_revenue|total_min|   revenue_per_min|   revenue_per_day|
+------------+------------------+---------+------------------+------------------+
|         148|  7173216.48999992|  3850676|1.8628460275546217|2682.4982796786553|
|         243| 796995.7299999984|   524808|1.5186424940168564| 2186.845191384273|
|          31|24943.809999999998|    18552| 1.344534821043553|1936.1301423027166|
|         137|5912935.3600000935|  3625831|1.6307807396428828|2348.3242650857514|
|          85|         278465.54|   278239|1.0008141921154114|1441.1724366461924|
|         251|           6042.42|     2788|2.1672955523672885|3120.9055954088954|
|          65| 879406.6699999995|   599500|1.4669002001668048| 2112.336288240199|
|         255| 1637274.800000008|   927572|1.7651188263552673| 2541.771109951585|
|          53| 68854.93000000002|    50923|1.3521381301180218|1947.0789073699516|
|         133|185070.09000000005|   153103|1.2087946676420454|1740.6643214045453|
|          78|213430.45999999985|   233051|0.9158101016515692|1318.7665463782596|
|         108|          109733.4|   134219| 0.817569792652307| 1177.300501419322|
|         155|         195423.19|   215876|0.9052566751283144|1303.5696121847727|
|         211|4219655.2500000205|  2418702|1.7445949314963234| 2512.216701354706|
|         193|371513.88999999984|   251882| 1.474952120437347|2123.9310534297797|
|          34|161259.31999999995|    77616|2.0776556380127804|2991.8241187384037|
|         101|          74016.35|    51283|1.4432921240957044|2078.3406586978144|
|         126|138466.63999999998|   126707|1.0928097105921535| 1573.645983252701|
|          81|153490.22000000003|   168496|0.9109428116987942|1311.7576488462637|
|         210|202727.58999999994|   239962|0.8448320567423173| 1216.558161708937|
+------------+------------------+---------+------------------+------------------+
only showing top 20 rows

In [7]:
import geopandas as gpd
taxi_zones = gpd.read_file('data/taxi_zones/taxi_zones.shp')
print(taxi_zones.dtypes)
taxi_zones.head()

OBJECTID         int32
Shape_Leng     float64
Shape_Area     float64
zone               str
LocationID       int32
borough            str
geometry      geometry
dtype: object

,OBJECTID,Shape_Leng,Shape_Area,zone,LocationID,borough,geometry
0,1,0.116357,0.000782,Newark Airport,1,EWR,"POLYGON ((933100.918 192536.086, 933091.011 19..."
1,2,0.433470,0.004866,Jamaica Bay,2,Queens,"MULTIPOLYGON (((1033269.244 172126.008, 103343..."
2,3,0.084341,0.000314,Allerton/Pelham Gardens,3,Bronx,"POLYGON ((1026308.77 256767.698, 1026495.593 2..."
3,4,0.043567,0.000112,Alphabet City,4,Manhattan,"POLYGON ((992073.467 203714.076, 992068.667 20..."
4,5,0.092146,0.000498,Arden Heights,5,Staten Island,"POLYGON ((935843.31 144283.336, 936046.565 144..."

In [8]:
neighbours = gpd.sjoin(
    taxi_zones[['OBJECTID', 'geometry']],
    taxi_zones[['OBJECTID', 'geometry']],
    how='left',
    predicate='touches'
)
neighbours_id = (
    neighbours
    .groupby('OBJECTID_left')['OBJECTID_right']
    .agg(list)
    .reset_index()
    .rename(columns={'OBJECTID_left': 'ID', 'OBJECTID_right': 'neighbour_ID'})
)
print(neighbours_id.dtypes)
neighbours_id

ID               int32
neighbour_ID    object
dtype: object

      ID                        neighbour_ID
0      1                               [nan]
1      2                             [132.0]
2      3         [242.0, 184.0, 51.0, 254.0]
3      4                [148.0, 79.0, 224.0]
4      5                               [nan]
..   ...                                 ...
258  259                             [254.0]
259  260                             [157.0]
260  261                [88.0, 209.0, 231.0]
261  262         [140.0, 141.0, 263.0, 75.0]
262  263  [140.0, 141.0, 262.0, 236.0, 75.0]

[263 rows x 2 columns]

In [9]:
import math
from pyspark.sql.types import (
    StructType,
    StructField,
    IntegerType,
    ArrayType
)
from pyspark.sql import functions as F


# ============================================================
# 1. Convert GeoPandas neighbour data into Python records
# ============================================================

records = []

for _, row in neighbours_id.iterrows():

    neighbour_list = row["neighbour_ID"]

    # Remove NaN values from the neighbour list
    if isinstance(neighbour_list, list):
        cleaned_neighbours = [
            int(x)
            for x in neighbour_list
            if x is not None
            and not (isinstance(x, float) and math.isnan(x))
        ]
    else:
        cleaned_neighbours = []

    records.append(
        (
            int(row["ID"]),
            cleaned_neighbours
        )
    )


# ============================================================
# 2. Create Spark DataFrame containing the neighbours
# ============================================================

neighbour_schema = StructType([
    StructField(
        "ID",
        IntegerType(),
        nullable=False
    ),
    StructField(
        "neighbour_ID",
        ArrayType(IntegerType()),
        nullable=True
    )
])

neighbours_spark = spark.createDataFrame(
    records,
    schema=neighbour_schema
)


# ============================================================
# 3. Turn each neighbour in the list into its own row
# ============================================================

neighbours_exploded = neighbours_spark.select(
    "ID",
    F.explode("neighbour_ID").alias("neighbour_ID")
)


# ============================================================
# 4. Get revenue_per_min for each neighbour
# ============================================================

neighbour_revenue = neighbours_exploded.join(
    zone_stats.select(
        F.col("PULocationID"),
        F.col("revenue_per_min").alias(
            "neighbour_revenue_per_min"
        )
    ),
    neighbours_exploded["neighbour_ID"]
        == F.col("PULocationID"),
    how="left"
)


# ============================================================
# 5. Calculate average revenue_per_min across neighbours
# ============================================================

expected_revenue = neighbour_revenue.groupBy(
    "ID"
).agg(
    F.avg(
        "neighbour_revenue_per_min"
    ).alias(
        "expected_revenue_per_min"
    )
)


# ============================================================
# 6. Add expected revenue back onto zone_stats
# ============================================================

zone_stats = zone_stats.join(
    expected_revenue,
    zone_stats["PULocationID"]
        == expected_revenue["ID"],
    how="left"
).drop(
    expected_revenue["ID"]
)


# ============================================================
# 7. Check the result
# ============================================================

zone_stats.select(
    "PULocationID",
    "revenue_per_min",
    "expected_revenue_per_min",
).show()

+------------+------------------+------------------------+
|PULocationID|   revenue_per_min|expected_revenue_per_min|
+------------+------------------+------------------------+
|         148|1.8628460275546217|      1.7194977396183613|
|         243|1.5186424940168564|                    NULL|
|          31| 1.344534821043553|      0.9403038098092695|
|         137|1.6307807396428828|      1.7571796665882706|
|          85|1.0008141921154114|      0.9850897797601564|
|         251|2.1672955523672885|       2.123026316640638|
|          65|1.4669002001668048|      1.3531411411908931|
|         255|1.7651188263552673|      1.6643003281063158|
|          53|1.3521381301180218|       2.239888663316662|
|         133|1.2087946676420454|      0.9319665062873244|
|          78|0.9158101016515692|       0.947592135434454|
|         108| 0.817569792652307|      0.8265202127016739|
|         155|0.9052566751283144|      0.8411457014364051|
|         211|1.7445949314963234|      1.7778007934159596|
|         193| 1.474952120437347|      1.8127488873002355|
|          34|2.0776556380127804|      1.3739070830882298|
|         101|1.4432921240957044|                    NULL|
|         126|1.0928097105921535|       1.049888257166544|
|          81|0.9109428116987942|        0.90551702011614|
|         210|0.8448320567423173|      0.8035030784975137|
+------------+------------------+------------------------+
only showing top 20 rows

In [10]:
zone_stats = zone_stats.withColumn(
    "underperformance_pct",
    ((F.col("expected_revenue_per_min") - F.col("revenue_per_min")) 
     / F.col("expected_revenue_per_min") * 100)
)

zone_stats = zone_stats.withColumn(
    "is_underperformer",
    F.col("underperformance_pct") > 10  # Flag zones >10% below neighbors
)

In [19]:
city_avg = zone_stats.agg(
    F.avg("revenue_per_min").alias("city_avg_revenue")
).collect()[0][0]

zone_stats = zone_stats.withColumn(
    "city_avg_revenue",
    F.lit(city_avg)
).withColumn(
    "below_city_avg_pct",
    ((F.col("city_avg_revenue") - F.col("revenue_per_min")) 
     / F.col("city_avg_revenue") * 100)
)
print(zone_stats.count())
zone_stats.show()

262

+------------+------------------+---------+------------------+------------------+------------------------+--------------------+-----------------+------------------+-------------------+
|PULocationID|     total_revenue|total_min|   revenue_per_min|   revenue_per_day|expected_revenue_per_min|underperformance_pct|is_underperformer|  city_avg_revenue| below_city_avg_pct|
+------------+------------------+---------+------------------+------------------+------------------------+--------------------+-----------------+------------------+-------------------+
|         148|  7173216.48999992|  3850676|1.8628460275546217|2682.4982796786553|      1.7194977396183613|  -8.336637183836965|            false|1.8825962772551676| 1.0490963962460336|
|         243| 796995.7299999984|   524808|1.5186424940168564| 2186.845191384273|                    NULL|                NULL|             NULL|1.8825962772551676| 19.332545572062706|
|          31|24943.809999999998|    18552| 1.344534821043553|1936.1301423027166|      0.9403038098092695|   -42.9894048090986|            false|1.8825962772551676| 28.580820153119085|
|         137|5912935.3600000935|  3625831|1.6307807396428828|2348.3242650857514|      1.7571796665882706|   7.193284178549778|            false|1.8825962772551676| 13.375971293188405|
|          85|         278465.54|   278239|1.0008141921154114|1441.1724366461924|      0.9850897797601564| -1.5962415485706791|            false|1.8825962772551676| 46.838618337511946|
|         251|           6042.42|     2788|2.1672955523672885|3120.9055954088954|       2.123026316640638| -2.0851948645036007|            false|1.8825962772551676|-15.122694045013915|
|          65| 879406.6699999995|   599500|1.4669002001668048| 2112.336288240199|      1.3531411411908931|  -8.407035712164722|            false|1.8825962772551676| 22.080999633891196|
|         255| 1637274.800000008|   927572|1.7651188263552673| 2541.771109951585|      1.6643003281063158|  -6.057710651518372|            false|1.8825962772551676|    6.2401828963129|
|          53| 68854.93000000002|    50923|1.3521381301180218|1947.0789073699516|       2.239888663316662|   39.63369018012372|             true|1.8825962772551676|  28.17694656820186|
|         133|185070.09000000005|   153103|1.2087946676420454|1740.6643214045453|      0.9319665062873244| -29.703659894122325|            false|1.8825962772551676| 35.791083715278965|
|          78|213430.45999999985|   233051|0.9158101016515692|1318.7665463782596|       0.947592135434454|   3.353978214299268|            false|1.8825962772551676| 51.353876945575195|
|         108|          109733.4|   134219| 0.817569792652307| 1177.300501419322|      0.8265202127016739|  1.0829039522349158|            false|1.8825962772551676| 56.572218774153384|
|         155|         195423.19|   215876|0.9052566751283144|1303.5696121847727|      0.8411457014364051|  -7.621863082986515|            false|1.8825962772551676| 51.914455262379356|
|         211|4219655.2500000205|  2418702|1.7445949314963234| 2512.216701354706|      1.7778007934159596|  1.8678055518151038|            false|1.8825962772551676| 7.3303738792074284|
|         193|371513.88999999984|   251882| 1.474952120437347|2123.9310534297797|      1.8127488873002355|  18.634504162679487|             true|1.8825962772551676|  21.65329665966233|
|          34|161259.31999999995|    77616|2.0776556380127804|2991.8241187384037|      1.3739070830882298| -51.222427163173535|            false|1.8825962772551676| -10.36118912558406|
|         101|          74016.35|    51283|1.4432921240957044|2078.3406586978144|                    NULL|                NULL|             NULL|1.8825962772551676| 23.335016565525688|
|         126|138466.63999999998|   126707|1.0928097105921535| 1573.645983252701|       1.049888257166544|  -4.088192541694545|            false|1.8825962772551676|   41.9519881243219|
|          81|153490.22000000003|   168496|0.9109428116987942|1311.7576488462637|        0.90551702011614| -0.5991926669648145|            false|1.8825962772551676|  51.61241830208269|
|         210|202727.58999999994|   239962|0.8448320567423173| 1216.558161708937|      0.8035030784975137|  -5.143599240725438|            false|1.8825962772551676| 55.124098196237505|
+------------+------------------+---------+------------------+------------------+------------------------+--------------------+-----------------+------------------+-------------------+
only showing top 20 rows

In [12]:
raw_weather_data = spark.read.csv("data/weather.csv", header=True, inferSchema=True)
print(raw_weather_data.columns)

['STATION', 'NAME', 'DATE', 'AWND', 'DAPR', 'MDPR', 'PRCP', 'SNOW', 'SNWD', 'TAVG', 'TMAX', 'TMIN', 'TOBS', 'WDF2', 'WDF5', 'WESD', 'WESF', 'WSF2', 'WSF5', 'WT01', 'WT02', 'WT03', 'WT04', 'WT05', 'WT06', 'WT08', 'WT09', 'WT11']

In [13]:
raw_weather_data = raw_weather_data.filter(
    F.col('STATION').isin(['USW00014732', 'USW00094789'])  # LaGuardia + JFK
)

In [14]:
weather_df = raw_weather_data.filter(raw_weather_data['NAME'].contains('LAGUARDIA')).select('DATE', 'PRCP', 'SNOW', 'TMAX', 'TMIN')
weather_df = weather_df.withColumn('TAVG', (F.col('TMAX') + F.col('TMIN')) / 2)
weather_df.show()

+----------+----+----+----+----+----+
|      DATE|PRCP|SNOW|TMAX|TMIN|TAVG|
+----------+----+----+----+----+----+
|2026-01-01| 0.0| 0.0|  36|  23|29.5|
|2026-01-02| 0.0| 0.0|  30|  20|25.0|
|2026-01-03| 0.0| 0.0|  31|  24|27.5|
|2026-01-04| 0.0| 0.0|  35|  26|30.5|
|2026-01-05| 0.0| 0.0|  38|  30|34.0|
|2026-01-06|0.01| 0.0|  39|  35|37.0|
|2026-01-07|0.01| 0.0|  48|  36|42.0|
|2026-01-08| 0.0| 0.0|  50|  37|43.5|
|2026-01-09| 0.0| 0.0|  54|  35|44.5|
|2026-01-10|0.46| 0.0|  53|  38|45.5|
|2026-01-11|0.02| 0.0|  47|  34|40.5|
|2026-01-12| 0.0| 0.0|  41|  32|36.5|
|2026-01-13| 0.0| 0.0|  47|  37|42.0|
|2026-01-14| 0.0| 0.0|  51|  42|46.5|
|2026-01-15| 0.0| 0.0|  46|  25|35.5|
|2026-01-16| 0.0| 0.0|  34|  22|28.0|
|2026-01-17|0.17| 1.4|  40|  31|35.5|
|2026-01-18|0.26| 1.5|  35|  31|33.0|
|2026-01-19| 0.0| 0.0|  33|  24|28.5|
|2026-01-20| 0.0| 0.0|  27|  17|22.0|
+----------+----+----+----+----+----+
only showing top 20 rows

In [15]:
# Get your underperformers from Phase 3
underperformers = zone_stats.filter(
    (F.col('underperformance_pct') > 8) &
    (F.col('below_city_avg_pct') > 10)
).select('PULocationID').collect()

underperformer_ids = [row.PULocationID for row in underperformers]

# Now filter taxi data to only these zones
taxi_underperformers = data1.filter(
    F.col('PULocationID').isin(underperformer_ids)
)
taxi_underperformers.show()

+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+---------------+
|VendorID|tpep_pickup_datetime|tpep_dropoff_datetime|passenger_count|trip_distance|RatecodeID|store_and_fwd_flag|PULocationID|DOLocationID|payment_type|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|congestion_surcharge|Airport_fee|cbd_congestion_fee|duration_minute|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+---------------+
|       2| 2026-01-01 00:42:34|  2026-01-01 00:47:15|              1|         0.55|         1|                 N|         140|         237|           1|        5.8|  1.0|    0.5|      1.08|         0.0|                  1.0|       11.88|                 2.5|        0.0|               0.0|              4|
|       2| 2026-01-01 00:33:44|  2026-01-01 00:51:34|              1|          2.8|         1|                 N|         140|          79|           1|       17.7|  1.0|    0.5|      5.86|         0.0|                  1.0|       29.31|                 2.5|        0.0|              0.75|             17|
|       1| 2026-01-01 00:49:04|  2026-01-01 01:36:01|              1|         19.1|         4|                 N|         140|         265|           2|       80.0| 4.25|    0.5|       0.0|         0.0|                  1.0|       85.75|                 2.5|        0.0|              0.75|             46|
|       2| 2026-01-01 00:30:32|  2026-01-01 00:37:22|              1|         1.79|         1|                 N|         140|          75|           1|       10.0|  1.0|    0.5|       3.0|         0.0|                  1.0|        18.0|                 2.5|        0.0|               0.0|              6|
|       1| 2026-01-01 00:59:22|  2026-01-01 01:07:58|              0|          1.3|         1|                 N|          75|         151|           2|       10.0|  1.0|    0.5|       0.0|         0.0|                  1.0|        12.5|                 0.0|        0.0|               0.0|              8|
|       2| 2026-01-01 00:41:31|  2026-01-01 00:50:01|              1|         1.28|         1|                 N|          75|          41|           2|       10.0|  1.0|    0.5|       0.0|         0.0|                  1.0|        12.5|                 0.0|        0.0|               0.0|              8|
|       2| 2026-01-01 00:30:55|  2026-01-01 00:36:42|              1|          1.4|         1|                 N|          75|         262|           1|        8.6|  1.0|    0.5|      2.72|         0.0|                  1.0|       16.32|                 2.5|        0.0|               0.0|              5|
|       2| 2026-01-01 00:41:25|  2026-01-01 00:56:38|              1|         2.73|         1|                 N|         140|         238|           1|       17.0|  1.0|    0.5|       4.4|         0.0|                  1.0|        26.4|                 2.5|        0.0|               0.0|             15|
|       2| 2026-01-01 00:30:35|  2026-01-01 00:44:42|              1|         3.65|         1|                 N|         140|          41|           2|       17.7|  1.0|    0.5|       0.0|         0.0|                  1.0|        22.7|                 2.5|        0.0|               0.0|             14|
|       2| 2026-01-01 00:34:00|  2026-01-01 00:38:33|              3|         0.79|         1|                 N|         140|         263|           1|        6.5|  1.0|    0.5|       2.3|         0.0|                  1.0|        13.8|                 2.5|        0.0|               0.0|              4|
|       2| 2026-01-01 00:37:48|  2026-01-01 01:05:41|              1|          3.4|         1|                 N|          75|         233|           1|       26.1|  1.0|    0.5|      10.0|         0.0|                  1.0|       41.85|                 2.5|        0.0|              0.75|             27|
|       7| 2026-01-01 00:22:40|  2026-01-01 00:22:40|              2|         1.24|         1|                 N|         140|         236|           1|        8.6|  0.0|    0.5|      2.72|         0.0|                  1.0|       16.32|                 2.5|        0.0|               0.0|              0|
|       2| 2026-01-01 00:06:52|  2026-01-01 00:18:40|              2|         2.45|         1|                 N|         140|         238|           1|       14.9|  1.0|    0.5|      3.98|         0.0|                  1.0|       23.88|                 2.5|        0.0|               0.0|             11|
|       2| 2026-01-01 00:34:58|  2026-01-01 00:54:42|              2|         4.12|         1|                 N|         140|         114|           1|       22.6|  1.0|    0.5|      5.67|         0.0|                  1.0|       34.02|                 2.5|        0.0|              0.75|             19|
|       2| 2026-01-01 00:26:55|  2026-01-01 00:31:47|              1|         0.97|         1|                 N|         140|         141|           1|        7.2|  1.0|    0.5|      3.66|         0.0|                  1.0|       15.86|                 2.5|        0.0|               0.0|              4|
|       1| 2026-01-01 00:37:53|  2026-01-01 00:48:14|              1|          1.4|         1|                 N|          75|          24|           1|       10.7|  1.0|    0.5|      2.65|         0.0|                  1.0|       15.85|                 0.0|        0.0|               0.0|             10|
|       2| 2026-01-01 00:41:35|  2026-01-01 00:56:07|              1|         2.65|         1|                 N|         140|         239|           1|       15.6|  1.0|    0.5|      4.12|         0.0|                  1.0|       24.72|                 2.5|        0.0|               0.0|             14|
|       2| 2026-01-01 00:44:13|  2026-01-01 00:51:22|              2|         1.18|         1|                 N|         140|         237|           1|        8.6|  1.0|    0.5|      2.72|         0.0|                  1.0|       16.32|                 2.5|        0.0|               0.0|              7|
|       2| 2026-01-01 00:40:53|  2026-01-01 00:53:43|              1|         2.54|         1|                 N|          75|          42|           1|       14.9|  1.0|    0.5|      3.48|         0.0|                  1.0|       20.88|                 0.0|        0.0|               0.0|             12|
|       2| 2026-01-01 00:10:42|  2026-01-01 00:24:15|              4|         1.95|         1|                 N|         140|         229|           1|       14.2|  1.0|    0.5|       3.0|         0.0|                  1.0|       22.95|                 2.5|        0.0|              0.75|             13|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+---------------+
only showing top 20 rows

In [16]:
from pyspark.sql.window import Window
import pyspark.sql.functions as F

w = Window.orderBy("date")

# choose desired zone to visualise
desired_underperformer = taxi_underperformers.filter(F.col("PULocationID") == 140)
# aggregate to a daily frequency
daily_revenue = desired_underperformer.groupBy(
    F.to_date('tpep_pickup_datetime').alias('date'),
    'PULocationID'
).agg(
    F.sum('total_amount').alias('daily_revenue'),
    F.count('*').alias('trip_count'),
    F.avg('total_amount').alias('avg_trip_revenue')
).orderBy('date')
daily_revenue.show()

+----------+------------+------------------+----------+------------------+
|      date|PULocationID|     daily_revenue|trip_count|  avg_trip_revenue|
+----------+------------+------------------+----------+------------------+
|2026-01-01|         140|32481.030000000035|      1393|23.317322325915317|
|2026-01-02|         140| 43681.00999999996|      1924| 22.70322765072763|
|2026-01-03|         140|32519.280000000028|      1482|21.942834008097186|
|2026-01-04|         140|27393.150000000023|      1279|21.417630961688836|
|2026-01-05|         140| 64206.22999999997|      2751| 23.33923300617956|
|2026-01-06|         140| 72347.66999999993|      3039| 23.80640671273443|
|2026-01-07|         140| 73551.28999999998|      3025|24.314476033057844|
|2026-01-08|         140| 74526.60999999996|      2999|24.850486828942966|
|2026-01-09|         140| 70137.26000000005|      2922|24.003169062286123|
|2026-01-10|         140| 49360.88999999997|      2164| 22.81002310536043|
|2026-01-11|         140| 35371.30999999997|      1653|21.398251663641844|
|2026-01-12|         140| 72945.28999999994|      3064| 23.80720953002609|
|2026-01-13|         140|          76153.35|      3140| 24.25265923566879|
|2026-01-14|         140|  78315.0800000002|      3197|  24.4964279011574|
|2026-01-15|         140| 83049.07000000004|      3387|24.519949808089766|
|2026-01-16|         140| 79290.99999999999|      3256|24.352272727272723|
|2026-01-17|         140| 41803.32999999998|      1871|22.342773917691062|
|2026-01-18|         140| 33250.40000000005|      1549|21.465719819238252|
|2026-01-19|         140| 36080.14999999998|      1678|21.501877234803324|
|2026-01-20|         140| 81282.06999999989|      3332|24.394378751500568|
+----------+------------+------------------+----------+------------------+
only showing top 20 rows

In [17]:
taxi_underperformers_sub = daily_revenue.withColumn("row_num", F.row_number().over(w))
taxi_underperformers_sub = taxi_underperformers_sub.filter((F.col("row_num") % 2) == 1).drop("row_num")

In [18]:
import pandas as pd
expected_val = zone_stats.filter(zone_stats.PULocationID == 140).select('expected_revenue_per_day').collect()[0][0]
# Convert PySpark DataFrame to Pandas for plotting
taxi_underperformers_sub = taxi_underperformers_sub.select("date", "daily_revenue") \
    .orderBy("date") \
    .toPandas()

# Plot
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(taxi_underperformers_sub["date"], taxi_underperformers_sub["daily_revenue"])
# Plot constant line
plt.plot(
    taxi_underperformers_sub["date"],
    [expected_val] * len(taxi_underperformers_sub),
    label="Expected Revenue per Min (Zone 140)"
)
plt.xlim(pd.Timestamp('2026-01-01'), pd.Timestamp('2026-05-31'))
plt.xlabel("Date")
plt.ylabel("Daily Revenue")
plt.title("Total Amount over Time for Taxi Underperformers")
plt.tight_layout()
plt.show()

{"ts": "2026-08-12 16:14:03.760", "level": "ERROR", "logger": "DataFrameQueryContextLogger", "msg": "[UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `expected_revenue_per_day` cannot be resolved. Did you mean one of the following? [`expected_revenue_per_min`, `revenue_per_day`, `revenue_per_min`, `total_revenue`, `city_avg_revenue`]. SQLSTATE: 42703", "context": {"file": "java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java", "line": "104)", "fragment": "col", "errorClass": "UNRESOLVED_COLUMN.WITH_SUGGESTION"}, "exception": {"class": "Py4JJavaError", "msg": "An error occurred while calling o398.select.\n: org.apache.spark.sql.AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `expected_revenue_per_day` cannot be resolved. Did you mean one of the following? [`expected_revenue_per_min`, `revenue_per_day`, `revenue_per_min`, `total_revenue`, `city_avg_revenue`]. SQLSTATE: 42703;\n'Project ['expected_revenue_per_day]\n+- Filter (PULocationID#136 = 140)\n   +- Project [PULocationID#136, total_revenue#285, total_min#284L, revenue_per_min#286, revenue_per_day#287, expected_revenue_per_min#321, underperformance_pct#486, is_underperformer#487, city_avg_revenue#524, (((city_avg_revenue#524 - revenue_per_min#286) / city_avg_revenue#524) * cast(100 as double)) AS below_city_avg_pct#525]\n      +- Project [PULocationID#136, total_revenue#285, total_min#284L, revenue_per_min#286, revenue_per_day#287, expected_revenue_per_min#321, underperformance_pct#486, is_underperformer#487, 1.8825962772551676 AS city_avg_revenue#524]\n         +- Project [PULocationID#136, total_revenue#285, total_min#284L, revenue_per_min#286, revenue_per_day#287, expected_revenue_per_min#321, underperformance_pct#486, (underperformance_pct#486 > cast(10 as double)) AS is_underperformer#487]\n            +- Project [PULocationID#136, total_revenue#285, total_min#284L, revenue_per_min#286, revenue_per_day#287, expected_revenue_per_min#321, (((expected_revenue_per_min#321 - revenue_per_min#286) / expected_revenue_per_min#321) * cast(100 as double)) AS underperformance_pct#486]\n               +- Project [PULocationID#136, total_revenue#285, total_min#284L, revenue_per_min#286, revenue_per_day#287, expected_revenue_per_min#321]\n                  +- Join LeftOuter, (PULocationID#136 = ID#316)\n                     :- Project [PULocationID#136, total_revenue#285, total_min#284L, revenue_per_min#286, ((revenue_per_min#286 * cast(24 as double)) * cast(60 as double)) AS revenue_per_day#287]\n                     :  +- Project [PULocationID#136, total_revenue#285, total_min#284L, (total_revenue#285 / cast(total_min#284L as double)) AS revenue_per_min#286]\n                     :     +- Project [PULocationID#136, sum(total_amount)#282 AS total_revenue#285, sum(duration_minute)#283L AS total_min#284L]\n                     :        +- Aggregate [PULocationID#136], [PULocationID#136, sum(total_amount#145) AS sum(total_amount)#282, sum(duration_minute#258L) AS sum(duration_minute)#283L]\n                     :           +- Project [VendorID#129, tpep_pickup_datetime#130, tpep_dropoff_datetime#131, passenger_count#132L, trip_distance#133, RatecodeID#134L, store_and_fwd_flag#135, PULocationID#136, DOLocationID#137, payment_type#138L, fare_amount#139, extra#140, mta_tax#141, tip_amount#142, tolls_amount#143, improvement_surcharge#144, total_amount#145, congestion_surcharge#146, Airport_fee#147, cbd_congestion_fee#148, timestampdiff(MINUTE, cast(tpep_pickup_datetime#130 as timestamp), cast(tpep_dropoff_datetime#131 as timestamp), Some(Australia/Melbourne)) AS duration_minute#258L]\n                     :              +- Union false, false\n                     :                 :- Relation [VendorID#129,tpep_pickup_datetime#130,tpep_dropoff_datetime#131,passenger_count#132L,trip_distance#133,RatecodeID#134L,store_and_fwd_flag#135,PULocationID#136,DOLocationID#137,payment_type#138L,fare_amount#139,extra#140,mta_tax#141,tip_amount#142,tolls_amount#143,improvement_surcharge#144,total_amount#145,congestion_surcharge#146,Airport_fee#147,cbd_congestion_fee#148] parquet\n                     :                 :- Relation [VendorID#149,tpep_pickup_datetime#150,tpep_dropoff_datetime#151,passenger_count#152L,trip_distance#153,RatecodeID#154L,store_and_fwd_flag#155,PULocationID#156,DOLocationID#157,payment_type#158L,fare_amount#159,extra#160,mta_tax#161,tip_amount#162,tolls_amount#163,improvement_surcharge#164,total_amount#165,congestion_surcharge#166,Airport_fee#167,cbd_congestion_fee#168] parquet\n                     :                 :- Relation [VendorID#169,tpep_pickup_datetime#170,tpep_dropoff_datetime#171,passenger_count#172L,trip_distance#173,RatecodeID#174L,store_and_fwd_flag#175,PULocationID#176,DOLocationID#177,payment_type#178L,fare_amount#179,extra#180,mta_tax#181,tip_amount#182,tolls_amount#183,improvement_surcharge#184,total_amount#185,congestion_surcharge#186,Airport_fee#187,cbd_congestion_fee#188] parquet\n                     :                 :- Relation [VendorID#189,tpep_pickup_datetime#190,tpep_dropoff_datetime#191,passenger_count#192L,trip_distance#193,RatecodeID#194L,store_and_fwd_flag#195,PULocationID#196,DOLocationID#197,payment_type#198L,fare_amount#199,extra#200,mta_tax#201,tip_amount#202,tolls_amount#203,improvement_surcharge#204,total_amount#205,congestion_surcharge#206,Airport_fee#207,cbd_congestion_fee#208] parquet\n                     :                 +- Relation [VendorID#209,tpep_pickup_datetime#210,tpep_dropoff_datetime#211,passenger_count#212L,trip_distance#213,RatecodeID#214L,store_and_fwd_flag#215,PULocationID#216,DOLocationID#217,payment_type#218L,fare_amount#219,extra#220,mta_tax#221,tip_amount#222,tolls_amount#223,improvement_surcharge#224,total_amount#225,congestion_surcharge#226,Airport_fee#227,cbd_congestion_fee#228] parquet\n                     +- Aggregate [ID#316], [ID#316, avg(neighbour_revenue_per_min#320) AS expected_revenue_per_min#321]\n                        +- Join LeftOuter, (neighbour_ID#319 = PULocationID#334)\n                           :- Project [ID#316, neighbour_ID#319]\n                           :  +- Generate explode(neighbour_ID#317), false, [neighbour_ID#319]\n                           :     +- LogicalRDD [ID#316, neighbour_ID#317], false\n                           +- Project [PULocationID#334, revenue_per_min#432 AS neighbour_revenue_per_min#320]\n                              +- Project [PULocationID#334, total_revenue#430, total_min#431L, revenue_per_min#432, ((revenue_per_min#432 * cast(24 as double)) * cast(60 as double)) AS revenue_per_day#433]\n                                 +- Project [PULocationID#334, total_revenue#430, total_min#431L, (total_revenue#430 / cast(total_min#431L as double)) AS revenue_per_min#432]\n                                    +- Project [PULocationID#334, sum(total_amount)#428 AS total_revenue#430, sum(duration_minute)#429L AS total_min#431L]\n                                       +- Aggregate [PULocationID#334], [PULocationID#334, sum(total_amount#343) AS sum(total_amount)#428, sum(duration_minute#427L) AS sum(duration_minute)#429L]\n                                          +- Project [VendorID#327, tpep_pickup_datetime#328, tpep_dropoff_datetime#329, passenger_count#330L, trip_distance#331, RatecodeID#332L, store_and_fwd_flag#333, PULocationID#334, DOLocationID#335, payment_type#336L, fare_amount#337, extra#338, mta_tax#339, tip_amount#340, tolls_amount#341, improvement_surcharge#342, total_amount#343, congestion_surcharge#344, Airport_fee#345, cbd_congestion_fee#346, timestampdiff(MINUTE, cast(tpep_pickup_datetime#328 as timestamp), cast(tpep_dropoff_datetime#329 as timestamp), Some(Australia/Melbourne)) AS duration_minute#427L]\n                                             +- Union false, false\n                                                :- Relation [VendorID#327,tpep_pickup_datetime#328,tpep_dropoff_datetime#329,passenger_count#330L,trip_distance#331,RatecodeID#332L,store_and_fwd_flag#333,PULocationID#334,DOLocationID#335,payment_type#336L,fare_amount#337,extra#338,mta_tax#339,tip_amount#340,tolls_amount#341,improvement_surcharge#342,total_amount#343,congestion_surcharge#344,Airport_fee#345,cbd_congestion_fee#346] parquet\n                                                :- Relation [VendorID#347,tpep_pickup_datetime#348,tpep_dropoff_datetime#349,passenger_count#350L,trip_distance#351,RatecodeID#352L,store_and_fwd_flag#353,PULocationID#354,DOLocationID#355,payment_type#356L,fare_amount#357,extra#358,mta_tax#359,tip_amount#360,tolls_amount#361,improvement_surcharge#362,total_amount#363,congestion_surcharge#364,Airport_fee#365,cbd_congestion_fee#366] parquet\n                                                :- Relation [VendorID#367,tpep_pickup_datetime#368,tpep_dropoff_datetime#369,passenger_count#370L,trip_distance#371,RatecodeID#372L,store_and_fwd_flag#373,PULocationID#374,DOLocationID#375,payment_type#376L,fare_amount#377,extra#378,mta_tax#379,tip_amount#380,tolls_amount#381,improvement_surcharge#382,total_amount#383,congestion_surcharge#384,Airport_fee#385,cbd_congestion_fee#386] parquet\n                                                :- Relation [VendorID#387,tpep_pickup_datetime#388,tpep_dropoff_datetime#389,passenger_count#390L,trip_distance#391,RatecodeID#392L,store_and_fwd_flag#393,PULocationID#394,DOLocationID#395,payment_type#396L,fare_amount#397,extra#398,mta_tax#399,tip_amount#400,tolls_amount#401,improvement_surcharge#402,total_amount#403,congestion_surcharge#404,Airport_fee#405,cbd_congestion_fee#406] parquet\n                                                +- Relation [VendorID#407,tpep_pickup_datetime#408,tpep_dropoff_datetime#409,passenger_count#410L,trip_distance#411,RatecodeID#412L,store_and_fwd_flag#413,PULocationID#414,DOLocationID#415,payment_type#416L,fare_amount#417,extra#418,mta_tax#419,tip_amount#420,tolls_amount#421,improvement_surcharge#422,total_amount#423,congestion_surcharge#424,Airport_fee#425,cbd_congestion_fee#426] parquet\n\n\tat org.apache.spark.sql.errors.QueryCompilationErrors$.unresolvedAttributeError(QueryCompilationErrors.scala:432)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.org$apache$spark$sql$catalyst$analysis$CheckAnalysis$$failUnresolvedAttribute(CheckAnalysis.scala:244)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$8(CheckAnalysis.scala:536)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$8$adapted(CheckAnalysis.scala:534)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:277)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7(CheckAnalysis.scala:534)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7$adapted(CheckAnalysis.scala:534)\n\tat scala.collection.immutable.List.foreach(List.scala:323)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2(CheckAnalysis.scala:534)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2$adapted(CheckAnalysis.scala:363)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:277)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:363)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:330)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:336)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:319)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:306)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:336)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$resolveInFixedPoint$1(HybridAnalyzer.scala:275)\n\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:275)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:82)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:117)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:75)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.runAnalysis$1(Analyzer.scala:368)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$2(Analyzer.scala:373)\n\tat org.apache.spark.sql.internal.SQLConf$.withExistingConf(SQLConf.scala:171)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.runWithSessionConf(Analyzer.scala:400)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:373)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:423)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:373)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:200)\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:148)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$3(QueryExecution.scala:410)\n\tat org.apache.spark.sql.execution.QueryExecution.withQueryExecutionId(QueryExecution.scala:429)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:410)\n\tat org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:872)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:409)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:810)\n\tat org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:408)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:200)\n\tat scala.util.Try$.apply(Try.scala:217)\n\tat org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1407)\n\tat org.apache.spark.util.Utils$.getTryWithCallerStacktrace(Utils.scala:1457)\n\tat org.apache.spark.util.LazyTry.get(LazyTry.scala:61)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:212)\n\tat org.apache.spark.sql.execution.QueryExecution.withAbortTransactionOnFailure(QueryExecution.scala:632)\n\tat org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:212)\n\tat org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:151)\n\tat org.apache.spark.sql.classic.Dataset$.$anonfun$ofRows$1(Dataset.scala:114)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:810)\n\tat org.apache.spark.sql.classic.Dataset$.ofRows(Dataset.scala:112)\n\tat org.apache.spark.sql.classic.Dataset.withPlan(Dataset.scala:2367)\n\tat org.apache.spark.sql.classic.Dataset.select(Dataset.scala:974)\n\tat org.apache.spark.sql.classic.Dataset.select(Dataset.scala:231)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:565)\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)\n\tat py4j.Gateway.invoke(Gateway.java:282)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:184)\n\tat py4j.ClientServerConnection.run(ClientServerConnection.java:108)\n\tat java.base/java.lang.Thread.run(Thread.java:1474)\n", "stacktrace": [{"class": null, "method": "deco", "file": "/home/aydin-khan/Documents/coding/applied-data-science-projects/applied-ds-env/lib/python3.14/site-packages/pyspark/errors/exceptions/captured.py", "line": "251"}, {"class": null, "method": "get_return_value", "file": "/home/aydin-khan/Documents/coding/applied-data-science-projects/applied-ds-env/lib/python3.14/site-packages/py4j/protocol.py", "line": "327"}]}}

AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `expected_revenue_per_day` cannot be resolved. Did you mean one of the following? [`expected_revenue_per_min`, `revenue_per_day`, `revenue_per_min`, `total_revenue`, `city_avg_revenue`]. SQLSTATE: 42703;
'Project ['expected_revenue_per_day]
+- Filter (PULocationID#136 = 140)
   +- Project [PULocationID#136, total_revenue#285, total_min#284L, revenue_per_min#286, revenue_per_day#287, expected_revenue_per_min#321, underperformance_pct#486, is_underperformer#487, city_avg_revenue#524, (((city_avg_revenue#524 - revenue_per_min#286) / city_avg_revenue#524) * cast(100 as double)) AS below_city_avg_pct#525]
      +- Project [PULocationID#136, total_revenue#285, total_min#284L, revenue_per_min#286, revenue_per_day#287, expected_revenue_per_min#321, underperformance_pct#486, is_underperformer#487, 1.8825962772551676 AS city_avg_revenue#524]
         +- Project [PULocationID#136, total_revenue#285, total_min#284L, revenue_per_min#286, revenue_per_day#287, expected_revenue_per_min#321, underperformance_pct#486, (underperformance_pct#486 > cast(10 as double)) AS is_underperformer#487]
            +- Project [PULocationID#136, total_revenue#285, total_min#284L, revenue_per_min#286, revenue_per_day#287, expected_revenue_per_min#321, (((expected_revenue_per_min#321 - revenue_per_min#286) / expected_revenue_per_min#321) * cast(100 as double)) AS underperformance_pct#486]
               +- Project [PULocationID#136, total_revenue#285, total_min#284L, revenue_per_min#286, revenue_per_day#287, expected_revenue_per_min#321]
                  +- Join LeftOuter, (PULocationID#136 = ID#316)
                     :- Project [PULocationID#136, total_revenue#285, total_min#284L, revenue_per_min#286, ((revenue_per_min#286 * cast(24 as double)) * cast(60 as double)) AS revenue_per_day#287]
                     :  +- Project [PULocationID#136, total_revenue#285, total_min#284L, (total_revenue#285 / cast(total_min#284L as double)) AS revenue_per_min#286]
                     :     +- Project [PULocationID#136, sum(total_amount)#282 AS total_revenue#285, sum(duration_minute)#283L AS total_min#284L]
                     :        +- Aggregate [PULocationID#136], [PULocationID#136, sum(total_amount#145) AS sum(total_amount)#282, sum(duration_minute#258L) AS sum(duration_minute)#283L]
                     :           +- Project [VendorID#129, tpep_pickup_datetime#130, tpep_dropoff_datetime#131, passenger_count#132L, trip_distance#133, RatecodeID#134L, store_and_fwd_flag#135, PULocationID#136, DOLocationID#137, payment_type#138L, fare_amount#139, extra#140, mta_tax#141, tip_amount#142, tolls_amount#143, improvement_surcharge#144, total_amount#145, congestion_surcharge#146, Airport_fee#147, cbd_congestion_fee#148, timestampdiff(MINUTE, cast(tpep_pickup_datetime#130 as timestamp), cast(tpep_dropoff_datetime#131 as timestamp), Some(Australia/Melbourne)) AS duration_minute#258L]
                     :              +- Union false, false
                     :                 :- Relation [VendorID#129,tpep_pickup_datetime#130,tpep_dropoff_datetime#131,passenger_count#132L,trip_distance#133,RatecodeID#134L,store_and_fwd_flag#135,PULocationID#136,DOLocationID#137,payment_type#138L,fare_amount#139,extra#140,mta_tax#141,tip_amount#142,tolls_amount#143,improvement_surcharge#144,total_amount#145,congestion_surcharge#146,Airport_fee#147,cbd_congestion_fee#148] parquet
                     :                 :- Relation [VendorID#149,tpep_pickup_datetime#150,tpep_dropoff_datetime#151,passenger_count#152L,trip_distance#153,RatecodeID#154L,store_and_fwd_flag#155,PULocationID#156,DOLocationID#157,payment_type#158L,fare_amount#159,extra#160,mta_tax#161,tip_amount#162,tolls_amount#163,improvement_surcharge#164,total_amount#165,congestion_surcharge#166,Airport_fee#167,cbd_congestion_fee#168] parquet
                     :                 :- Relation [VendorID#169,tpep_pickup_datetime#170,tpep_dropoff_datetime#171,passenger_count#172L,trip_distance#173,RatecodeID#174L,store_and_fwd_flag#175,PULocationID#176,DOLocationID#177,payment_type#178L,fare_amount#179,extra#180,mta_tax#181,tip_amount#182,tolls_amount#183,improvement_surcharge#184,total_amount#185,congestion_surcharge#186,Airport_fee#187,cbd_congestion_fee#188] parquet
                     :                 :- Relation [VendorID#189,tpep_pickup_datetime#190,tpep_dropoff_datetime#191,passenger_count#192L,trip_distance#193,RatecodeID#194L,store_and_fwd_flag#195,PULocationID#196,DOLocationID#197,payment_type#198L,fare_amount#199,extra#200,mta_tax#201,tip_amount#202,tolls_amount#203,improvement_surcharge#204,total_amount#205,congestion_surcharge#206,Airport_fee#207,cbd_congestion_fee#208] parquet
                     :                 +- Relation [VendorID#209,tpep_pickup_datetime#210,tpep_dropoff_datetime#211,passenger_count#212L,trip_distance#213,RatecodeID#214L,store_and_fwd_flag#215,PULocationID#216,DOLocationID#217,payment_type#218L,fare_amount#219,extra#220,mta_tax#221,tip_amount#222,tolls_amount#223,improvement_surcharge#224,total_amount#225,congestion_surcharge#226,Airport_fee#227,cbd_congestion_fee#228] parquet
                     +- Aggregate [ID#316], [ID#316, avg(neighbour_revenue_per_min#320) AS expected_revenue_per_min#321]
                        +- Join LeftOuter, (neighbour_ID#319 = PULocationID#334)
                           :- Project [ID#316, neighbour_ID#319]
                           :  +- Generate explode(neighbour_ID#317), false, [neighbour_ID#319]
                           :     +- LogicalRDD [ID#316, neighbour_ID#317], false
                           +- Project [PULocationID#334, revenue_per_min#432 AS neighbour_revenue_per_min#320]
                              +- Project [PULocationID#334, total_revenue#430, total_min#431L, revenue_per_min#432, ((revenue_per_min#432 * cast(24 as double)) * cast(60 as double)) AS revenue_per_day#433]
                                 +- Project [PULocationID#334, total_revenue#430, total_min#431L, (total_revenue#430 / cast(total_min#431L as double)) AS revenue_per_min#432]
                                    +- Project [PULocationID#334, sum(total_amount)#428 AS total_revenue#430, sum(duration_minute)#429L AS total_min#431L]
                                       +- Aggregate [PULocationID#334], [PULocationID#334, sum(total_amount#343) AS sum(total_amount)#428, sum(duration_minute#427L) AS sum(duration_minute)#429L]
                                          +- Project [VendorID#327, tpep_pickup_datetime#328, tpep_dropoff_datetime#329, passenger_count#330L, trip_distance#331, RatecodeID#332L, store_and_fwd_flag#333, PULocationID#334, DOLocationID#335, payment_type#336L, fare_amount#337, extra#338, mta_tax#339, tip_amount#340, tolls_amount#341, improvement_surcharge#342, total_amount#343, congestion_surcharge#344, Airport_fee#345, cbd_congestion_fee#346, timestampdiff(MINUTE, cast(tpep_pickup_datetime#328 as timestamp), cast(tpep_dropoff_datetime#329 as timestamp), Some(Australia/Melbourne)) AS duration_minute#427L]
                                             +- Union false, false
                                                :- Relation [VendorID#327,tpep_pickup_datetime#328,tpep_dropoff_datetime#329,passenger_count#330L,trip_distance#331,RatecodeID#332L,store_and_fwd_flag#333,PULocationID#334,DOLocationID#335,payment_type#336L,fare_amount#337,extra#338,mta_tax#339,tip_amount#340,tolls_amount#341,improvement_surcharge#342,total_amount#343,congestion_surcharge#344,Airport_fee#345,cbd_congestion_fee#346] parquet
                                                :- Relation [VendorID#347,tpep_pickup_datetime#348,tpep_dropoff_datetime#349,passenger_count#350L,trip_distance#351,RatecodeID#352L,store_and_fwd_flag#353,PULocationID#354,DOLocationID#355,payment_type#356L,fare_amount#357,extra#358,mta_tax#359,tip_amount#360,tolls_amount#361,improvement_surcharge#362,total_amount#363,congestion_surcharge#364,Airport_fee#365,cbd_congestion_fee#366] parquet
                                                :- Relation [VendorID#367,tpep_pickup_datetime#368,tpep_dropoff_datetime#369,passenger_count#370L,trip_distance#371,RatecodeID#372L,store_and_fwd_flag#373,PULocationID#374,DOLocationID#375,payment_type#376L,fare_amount#377,extra#378,mta_tax#379,tip_amount#380,tolls_amount#381,improvement_surcharge#382,total_amount#383,congestion_surcharge#384,Airport_fee#385,cbd_congestion_fee#386] parquet
                                                :- Relation [VendorID#387,tpep_pickup_datetime#388,tpep_dropoff_datetime#389,passenger_count#390L,trip_distance#391,RatecodeID#392L,store_and_fwd_flag#393,PULocationID#394,DOLocationID#395,payment_type#396L,fare_amount#397,extra#398,mta_tax#399,tip_amount#400,tolls_amount#401,improvement_surcharge#402,total_amount#403,congestion_surcharge#404,Airport_fee#405,cbd_congestion_fee#406] parquet
                                                +- Relation [VendorID#407,tpep_pickup_datetime#408,tpep_dropoff_datetime#409,passenger_count#410L,trip_distance#411,RatecodeID#412L,store_and_fwd_flag#413,PULocationID#414,DOLocationID#415,payment_type#416L,fare_amount#417,extra#418,mta_tax#419,tip_amount#420,tolls_amount#421,improvement_surcharge#422,total_amount#423,congestion_surcharge#424,Airport_fee#425,cbd_congestion_fee#426] parquet

In [ ]:
print(zone_stats.filter(zone_stats.PULocationID == 140).select('expected_revenue_per_day').collect()[0][0])

2626.864791833104